### ISSUE TITLE
¿?

### ISSUE THREAD

**Issue by MrBlasyMSK** [OguzhanUmutlu/SignToDiscord#1]
[11:15:37] [Server thread/INFO]: Loading SignToDiscord v1.0.0

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 4194304) (tried to allocate 7310315409581548104 bytes) in phar:///home/container/PocketMine-MP.phar/src/pocketmine/scheduler/AsyncWorker.php on line 63

**Comment by OguzhanUmutlu** [comment]
> [11:15:37] [Server thread/INFO]: Loading SignToDiscord v1.0.0
> 
> mmap() failed: [12] Cannot allocate memory
> 
> mmap() failed: [12] Cannot allocate memory
> 
> Fatal error: Out of memory (allocated 4194304) (tried to allocate 7310315409581548104 bytes) in phar:///home/container/PocketMine-MP.phar/src/pocketmine/scheduler/AsyncWorker.php on line 63

hmmmmmmmmmmmmmmmmmmmm, how 🤔

**Comment by OguzhanUmutlu** [comment]
fixed it i suppose.
